[project]
name = "stock-market"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "ipykernel>=6.29.5",
    "openpyxl>=3.1.5",
    "pyyaml>=6.0.2",
    "yfinance>=0.2.54",
]
